version: '3.9'
services:
  cache:
    image: oracle/database:12.1.0.2-ee
    container_name: oracle
    restart: always
    ports:
      - ${LISTENER_PORT}:1521
      - ${APP_PORT}:5500
    networks:
      - default
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata

networks:
  default:
    name: docker_oracle_network
    driver: bridge

volumes:
  data:
    name: docker_oracle_data
    driver: local
